version: 1.0.{build}

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

install:
  - choco install mono
  - choco install bazel

build_script:
  - bazel --output_base=$HOME/.cache/bazel --batch --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m run -s --config=ci --experimental_repository_cache="$HOME/.bazel_repository_cache" --local_resources=400,1,1.0 --test_tag_filters=-dev //examples/example_binary:hello
