package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_dotnet//dotnet/private:context.bzl", "core_context_data")

core_context_data(
    name = "core_context_data",
    execroot_pathmap = "C:\\Anta\\rules_dotnet\\examples"
)
